# Generated by Django 5.2.2 on 2025-09-25 15:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('ทั่วไป', 'ทั่วไป'), ('พิเศษ', 'พิเศษ')], default='ทั่วไป', max_length=20)),
                ('is_special', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='รหัสผ่าน')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทร')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่')),
            ],
            options={
                'verbose_name': 'พนักงาน',
                'verbose_name_plural': 'พนักงาน',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='รหัสการขาย')),
                ('sale_date', models.DateField(auto_now_add=True, verbose_name='วันที่ขาย')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='ค่าขนส่ง')),
                ('status', models.IntegerField(choices=[(0, 'สั่งซื้อสินค้า'), (1, 'แจ้งชำระเงิน'), (2, 'ยืนยันการโอน'), (3, 'รอการจัดส่ง'), (4, 'จัดส่งเสร็จสิ้น')], default=0, verbose_name='สถานะ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer', verbose_name='ลูกค้า')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employee', verbose_name='พนักงาน')),
            ],
            options={
                'verbose_name': 'การขายสินค้า',
                'verbose_name_plural': 'การขายสินค้า',
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='รหัสสินค้า')),
                ('product_name', models.CharField(default=None, max_length=100, verbose_name='ชื่อสินค้า')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ราคา')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='จำนวน')),
                ('weight', models.DecimalField(choices=[(1.0, '1 กก.'), (5.0, '5 กก.'), (15.0, '15 กก.'), (25.0, '25 กก.')], decimal_places=1, default=1.0, max_digits=5, verbose_name='น้ำหนัก')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='รูปสินค้า')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(unique=True, verbose_name='น้ำหนัก (กก.)')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='อัตราค่าขนส่ง (บาท)')),
            ],
            options={
                'verbose_name': 'อัตราค่าขนส่ง',
                'verbose_name_plural': 'อัตราค่าขนส่ง',
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='ชื่อร้านค้า')),
                ('number', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('address', models.TextField(default=None, verbose_name='ที่อยู่ร้านค้า')),
                ('bank_account', models.TextField(blank=True, max_length=100, null=True, verbose_name='บัญชีธนาคาร')),
                ('customergener_id', models.CharField(default=None, max_length=20, verbose_name='รหัสลูกค้าทั่วไป')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expire_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.sale', verbose_name='รหัสการขายสินค้า')),
                ('pay_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, verbose_name='ยอดชำระเงิน')),
                ('pay_type', models.IntegerField(choices=[(0, 'โอนเงิน'), (1, 'จ่ายเงินปลายทาง')], default=0, verbose_name='ประเภทการชำระเงิน')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ชำระเงิน')),
                ('slip_image', models.ImageField(blank=True, null=True, upload_to='payment_slips/', verbose_name='รูปภาพสลิป')),
            ],
            options={
                'verbose_name': 'ข้อมูลการชำระเงิน',
                'verbose_name_plural': 'ข้อมูลการชำระเงิน',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='รหัสการจัดส่ง')),
                ('delivery_date', models.DateField(auto_now_add=True, verbose_name='วันที่จัดส่ง')),
                ('tracking_number', models.CharField(max_length=100, verbose_name='หมายเลขพัสดุ')),
                ('company', models.CharField(default=None, max_length=100, verbose_name='บริษัทขนส่ง')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='myapp.sale')),
            ],
            options={
                'verbose_name': 'การจัดส่ง',
                'verbose_name_plural': 'การจัดส่ง',
            },
        ),
        migrations.CreateModel(
            name='ProductReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_id', models.CharField(max_length=20, unique=True)),
                ('receive_date', models.DateField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReceiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.productreceive')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('quantity', models.IntegerField(verbose_name='จำนวน')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product', verbose_name='สินค้า')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.sale', verbose_name='รหัสการขาย')),
            ],
            options={
                'verbose_name': 'รายการสินค้าในใบขาย',
                'verbose_name_plural': 'รายการสินค้าในใบขาย',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทร')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่')),
                ('position', models.CharField(choices=[('employee', 'พนักงาน'), ('admin', 'แอดมิน'), ('owner', 'เจ้าของกิจการ')], default='employee', max_length=20, verbose_name='ตำแหน่ง')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('confirmation_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='รหัสใบเสร็จ')),
                ('confirm_date', models.DateField(auto_now_add=True, verbose_name='วันที่ยืนยัน')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.payment', verbose_name='รหัสการขายสินค้า')),
            ],
            options={
                'verbose_name': 'การยืนยันการชำระเงิน',
                'verbose_name_plural': 'การยืนยันการชำระเงิน',
            },
        ),
    ]
