# Generated by Django 5.2.2 on 2025-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='ลูกค้าพิเศษ'),
        ),
    ]
