# Generated by Django 5.2.2 on 2025-09-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_customer_status_alter_customer_is_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(verbose_name='วันที่ขาย'),
        ),
    ]
