# Generated by Django 5.2.2 on 2025-09-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_hidden', False)), fields=('customer_id',), name='unique_visible_customer_id'),
        ),
    ]
