# Generated by Django 5.2.2 on 2025-09-27 11:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customer_unique_visible_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='customergener_id',
        ),
        migrations.AddField(
            model_name='store',
            name='general_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='myapp.customer', verbose_name='ลูกค้าทั่วไปร้านหน้า'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ขาย'),
        ),
    ]
