# Generated by Django 5.2.2 on 2025-09-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_store_customergener_id_store_general_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='general_customer',
            field=models.CharField(blank=True, default='000', max_length=10, null=True, verbose_name='รหัสลูกค้าทั่วไป (สำหรับการขายหน้าร้าน)'),
        ),
    ]
