# Generated by Django 5.2.2 on 2025-09-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_store_general_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(verbose_name='ที่อยู่ร้านค้า'),
        ),
        migrations.AlterField(
            model_name='store',
            name='bank_account',
            field=models.TextField(blank=True, null=True, verbose_name='บัญชีธนาคาร'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อร้านค้า'),
        ),
    ]
