# Generated by Django 5.2.2 on 2025-09-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("ยูคา", "ถ่านไม้ยูคา"),
                    ("โกงกาง", "ถ่านไม้โกงกาง"),
                    ("เกษตร", "ถ่านไม้เกษตร"),
                    ("มะขาม", "ถ่านไม้มะขาม"),
                ],
                default="ยูคา",
                max_length=20,
                verbose_name="หมวดหมู่สินค้า",
            ),
        ),
    ]
