# Generated by Django 5.2.6 on 2026-03-30 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='ที่อยู่จัดส่ง'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(default='pending', max_length=50, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='บริษัทขนส่ง'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='หมายเลขพัสดุ'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.IntegerField(choices=[(0, 'สั่งซื้อสินค้า'), (1, 'แจ้งชำระเงิน'), (2, 'ยืนยันการโอน'), (3, 'รอการจัดส่ง'), (4, 'จัดส่งเสร็จสิ้น')], default=0, verbose_name='สถานะ'),
        ),
    ]
