# Generated by Django 6.0.3 on 2026-04-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_qty_cartitem_quantity_cartitem_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('employee', 'พนักงาน'), ('admin', 'แอดมิน'), ('owner', 'เจ้าของกิจการ')], default='employee', max_length=20),
        ),
    ]
